import test from 'node:test';
import assert from 'node:assert/strict';
import { canonicalString, digest } from '../dist/canonical.js';
import { authorshipInputDigest, authorPlan, deriveTopology, firstUnsettledDecision, projectRef, resolvePrePlan, selectGear, settlementWitness, shadowPolicy, validateCurrentReportAdmission, validateRef, validateWave, validateReport, renderExplore, compileWavePlan, verifyWavePlan, reconcileWave, materializeRoleView } from '../dist/deliberation.js';
import { validatePlan } from '../dist/validator.js';
import { ONE_SHOT_ROLLOUT_GENERATION_FLOOR } from '../dist/one-shot.js';

const ref = (id, value = id) => ({ id, digest: digest(value), scope: 'test', bytes: canonicalString(value) });
const unsettled = { decisionUnsettled: true, explicitExplore: false, citedWitness: false, planEquivalent: false, containedDiscovery: false, openEnded: false, highStakes: false, openlyPhrased: false, namedDiscriminator: true };

test('identity and ref projection are canonical and mutation-safe', () => {
  const r = ref('intent', { b: 2, a: 1 });
  assert.equal(validateRef(r).ok, true);
  assert.deepEqual(projectRef(r).value, { id: 'intent', digest: r.digest, scope: 'test' });
  assert.notEqual(authorshipInputDigest({ runId: 'r', phaseId: 'p', intent: r, evidenceSnapshot: ref('e', 1), authorityDigest: digest('a'), policyVersion: ref('v', 1), settlements: [] }), authorshipInputDigest({ runId: 'r', phaseId: 'p', intent: r, evidenceSnapshot: ref('e', 1), authorityDigest: digest('a'), policyVersion: ref('v', 1), settlements: [ref('s', 1)] }));
});

test('frontier ordering and gear precedence are deterministic', () => {
  assert.equal(firstUnsettledDecision([{ key: 'z', prospectiveEffectFrontierOrdinal: 1, settled: false, witness: false }, { key: 'a', prospectiveEffectFrontierOrdinal: 1, settled: false, witness: false }]).key, 'a');
  assert.equal(selectGear({ ...unsettled, explicitExplore: true }), 'EXPLORE');
  assert.equal(selectGear({ ...unsettled, citedWitness: true }), 'DIRECT');
  assert.equal(selectGear({ ...unsettled, namedDiscriminator: true }), 'FOCUS');
  assert.equal(selectGear({ ...unsettled, decisionUnsettled: false }), 'DIRECT');
  assert.equal(settlementWitness({ ...unsettled, decisionUnsettled: false }), 'SETTLED');
  assert.notEqual(selectGear({ ...unsettled, namedDiscriminator: false, openEnded: true, highStakes: true, openlyPhrased: true }), 'EXPLORE');
});

test('resolvePrePlan is the single exact selection/authorship seam', () => {
  const frames = [0, 1, 2, 3].map((i) => ({ frameId: `f${i}`, tag: i === 3 ? 'design' : 'code', text: `frame-${i}` })).concat([{ frameId: 'wild', tag: 'wild', text: 'wild' }]);
  const policy = { version: ref('resolve-policy'), frameCatalog: frames, maxMaterialDecisions: 4, maxSettlementBytes: 1_000_000, maxResolvedRoleInputBytes: 1_000_000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 };
  const plan = validatePlan({ schema: 'lunacy-plan-v1', phaseId: 'resolve', steps: [{ stepId: 'deliver' }] }).plan;
  const input = { runId: 'resolve-run', phaseId: 'resolve', intent: ref('resolve-intent', plan), evidenceSnapshot: ref('resolve-snapshot'), authorityDigest: digest('resolve-authority'), policyVersion: policy.version, settlements: [] };
  const base = { decisionUnsettled: true, explicitExplore: false, citedWitness: false, planEquivalent: false, containedDiscovery: false, openEnded: false, highStakes: false, openlyPhrased: false, namedDiscriminator: false };
  const direct = resolvePrePlan(input, { ...base, decisionUnsettled: false }, policy);
  assert.equal(direct.kind, 'COMPLETE_PLAN'); assert.equal(direct.gear, 'DIRECT'); assert.equal(direct.plan.phaseId, plan.phaseId); assert.deepEqual(direct.plan.steps.map((step) => step.stepId), ['deliver']);
  const ambiguous = resolvePrePlan(input, { ...base, openEnded: true, highStakes: true, openlyPhrased: true }, policy);
  assert.equal(ambiguous.kind, 'NO_SETTLEMENT');
  const focus = resolvePrePlan({ ...input, policyVersion: { ...policy.version } }, { ...base, namedDiscriminator: true }, { ...policy, frameCatalog: [] });
  assert.equal(focus.kind, 'DELIBERATION_REQUIRED'); assert.equal(focus.gear, 'FOCUS');
  const focusWave = JSON.parse(focus.wave.bytes); assert.deepEqual(focusWave.generatorLenses, [{ text: 'counterexample' }, { text: 'simplify' }]); assert.equal(focusWave.limits.maxModelCalls, 3); assert.equal(deriveTopology(focus.wave, focusWave).slots.length, 3);
  const explore = resolvePrePlan(input, { ...base, explicitExplore: true }, policy);
  assert.equal(explore.kind, 'DELIBERATION_REQUIRED'); assert.equal(explore.gear, 'EXPLORE');
  const exploreWave = JSON.parse(explore.wave.bytes); assert.equal(exploreWave.generatorLenses.length, 5); assert.equal(exploreWave.limits.maxModelCalls, 9); assert.equal(deriveTopology(explore.wave, exploreWave).slots.length, 9);
});

test('Focus reader union and current command admission resolve the two-lens collision by rollout context', () => {
  const policy = { version: ref('collision-policy'), frameCatalog: [], maxMaterialDecisions: 4, maxSettlementBytes: 1_000_000, maxResolvedRoleInputBytes: 1_000_000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 };
  const input = { runId: 'collision-run', phaseId: 'collision', intent: ref('collision-intent'), evidenceSnapshot: ref('collision-snapshot'), authorityDigest: digest('collision-authority'), policyVersion: policy.version, settlements: [] };
  const predicates = { ...unsettled, namedDiscriminator: true };
  const authored = resolvePrePlan(input, predicates, policy); assert.equal(authored.kind, 'DELIBERATION_REQUIRED');
  const wave = JSON.parse(authored.wave.bytes); const topology = deriveTopology(authored.wave, wave);
  const generators = [0, 1].map((slotOrdinal) => ({ schema: 'lunacy-deliberation-report/v2', wave: authored.wave, slotOrdinal, ideas: [{ text: `candidate-${slotOrdinal}`, rationale: 'because' }] }));
  const reportRef = (report) => ({ id: `report:${digest(report).slice(0, 16)}`, digest: digest(report), scope: 'deliberation/report', bytes: canonicalString(report) });
  const locators = generators.map((generator) => ({ generatorReport: reportRef(generator), oneBasedOrdinal: 1 }));
  const scores = locators.map((idea) => ({ idea, novelty: 8, viability: 8, fit: 8, evidence: [] }));
  const canonical = { schema: 'lunacy-deliberation-report/v2', wave: authored.wave, slotOrdinal: 2, scores, clusters: [{ label: 'a', ideas: [locators[0]] }, { label: 'b', ideas: [locators[1]] }] };
  const legacy = { ...canonical, clusters: [{ label: 'a', ideas: [locators[0]] }, { label: 'b', ideas: [locators[1]] }, { label: 'c', ideas: [] }] };
  const accepted = new Map(generators.map((report) => { const bound = reportRef(report); return [canonicalString({ id: bound.id, digest: bound.digest, scope: bound.scope }), { ref: bound, report, receipt: { commandDigest: digest(`command-${report.slotOrdinal}`), resultDigest: bound.digest, attemptEpoch: 0 } }]; }));
  const role = materializeRoleView({ waveRef: authored.wave, wave, slot: topology.slots[2], predecessorRefs: generators.map(reportRef), acceptedReportsByRef: accepted, resolved: new Map(), policy });
  assert.equal(role.ok, true); assert.match(role.value.contract, /one or two non-empty comparison groups/);
  const roleBytes = canonicalString(role.value); const roleView = { id: `role-view:${digest(role.value)}`, digest: digest(role.value), scope: 'deliberation/role-view', bytes: roleBytes };
  const context = { waveRef: authored.wave, wave, slot: topology.slots[2], predecessors: generators, policy, roleView, rolloutFloor: ONE_SHOT_ROLLOUT_GENERATION_FLOOR };
  assert.equal(validateReport(canonical, context).ok, true); assert.equal(validateReport(legacy, context).ok, true);
  assert.equal(validateCurrentReportAdmission(canonical, { ...context, rolloutGeneration: ONE_SHOT_ROLLOUT_GENERATION_FLOOR }).ok, true);
  assert.equal(validateCurrentReportAdmission(legacy, { ...context, rolloutGeneration: ONE_SHOT_ROLLOUT_GENERATION_FLOOR }).ok, false);
  assert.equal(validateCurrentReportAdmission(legacy, { ...context, rolloutGeneration: ONE_SHOT_ROLLOUT_GENERATION_FLOOR - 1 }).ok, true);
});

test('topology is derived from wave gear and stable slot ids', () => {
  const waveRef = ref('wave', 1);
  const base = { schema: 'lunacy-deliberation-wave/v2', authorship: { runId: 'r', phaseId: 'p', intent: ref('i'), evidenceSnapshot: ref('e'), authorityDigest: digest('a'), policyVersion: ref('v'), settlementPrefixDigest: digest('s'), decisionKey: 'd', prospectiveEffectFrontierOrdinal: 0 }, question: { text: 'q', decisionImpact: 'i', evidence: [], constraints: [] }, limits: { maxModelCalls: 9, maxWaveBytes: 100000, maxRefs: 20, maxResolvedRoleInputBytes: 100000, maxReportBytes: 100000, maxTotalReportBytes: 100000 } };
  const explore = deriveTopology(waveRef, { ...base, gear: 'EXPLORE', generatorLenses: [{ frameId: 'a' }, { frameId: 'b' }, { frameId: 'c' }, { frameId: 'd' }, { frameId: 'w' }] });
  assert.equal(explore.slots.length, 9);
  assert.equal(explore.slots.every((slot) => slot.route.model === 'gpt-5.6-luna' && slot.route.effort === 'max'), true);
  assert.deepEqual(explore.slots[5].dependencies, [0, 1, 2, 3, 4]);
  assert.equal(explore.edges.length, 8);
});

test('shadow OFF is a true no-op and SHADOW is pure diagnostic', () => {
  const input = { authorship: { runId: 'r', phaseId: 'p', intent: ref('i'), evidenceSnapshot: ref('e'), authorityDigest: digest('a'), policyVersion: ref('v'), settlements: [] }, predicates: { ...unsettled } };
  let calls = 0;
  assert.deepEqual(shadowPolicy({ ...input, mode: 'OFF', sink: () => { calls += 1; } }), { mode: 'OFF' });
  assert.equal(calls, 0);
  const result = shadowPolicy({ ...input, mode: 'SHADOW', policy: { version: ref('v'), frameCatalog: [], maxMaterialDecisions: 1, maxSettlementBytes: 10000, maxResolvedRoleInputBytes: 10000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 }, sink: () => { calls += 1; } });
  assert.equal(result.mode, 'SHADOW');
  assert.equal(calls, 1);
});

test('valid Focus ladder validates, compiles parent-gated topology, and rejects role drift', () => {
  const policy = { version: ref('v'), frameCatalog: [], maxMaterialDecisions: 4, maxSettlementBytes: 1_000_000, maxResolvedRoleInputBytes: 1_000_000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 };
  const wave = { schema: 'lunacy-deliberation-wave/v2', authorship: { runId: 'r', phaseId: 'p', intent: ref('i'), evidenceSnapshot: ref('e'), authorityDigest: digest('a'), policyVersion: policy.version, settlementPrefixDigest: digest('s'), decisionKey: 'd', prospectiveEffectFrontierOrdinal: 0 }, question: { text: 'q', decisionImpact: 'impact', evidence: [], constraints: [] }, limits: { maxModelCalls: 3, maxWaveBytes: 1_000_000, maxRefs: 128, maxResolvedRoleInputBytes: 1_000_000, maxReportBytes: 200_000, maxTotalReportBytes: 1_000_000 }, gear: 'FOCUS', generatorLenses: [{ text: 'counterexample' }, { text: 'simplify' }] };
  const waveRef = ref('wave', wave); const ctx = { runId: 'r', phaseId: 'p', policy, committedEvidence: new Set(), reachableConstraints: new Set() }; assert.equal(validateWave(wave, ctx).ok, true);
  const topology = deriveTopology(waveRef, wave); const generators = [0, 1].map((slotOrdinal) => ({ schema: 'lunacy-deliberation-report/v2', wave: waveRef, slotOrdinal, ideas: [{ text: `idea-${slotOrdinal}`, rationale: 'because' }] }));
  const reportRef = (report) => ({ id: `report:${digest(report).slice(0, 16)}`, digest: digest(report), scope: 'deliberation/report', bytes: canonicalString(report) });
  const critic = { schema: 'lunacy-deliberation-report/v2', wave: waveRef, slotOrdinal: 2, scores: generators.map((g, i) => ({ idea: { generatorReport: reportRef(g), oneBasedOrdinal: 1 }, novelty: i + 5, viability: 8, fit: 7, evidence: [] })), clusters: [{ label: 'a', ideas: [{ generatorReport: reportRef(generators[0]), oneBasedOrdinal: 1 }] }, { label: 'b', ideas: [{ generatorReport: reportRef(generators[1]), oneBasedOrdinal: 1 }] }, { label: 'c', ideas: [] }] };
  assert.equal(validateReport(generators[0], { waveRef, wave, slot: topology.slots[0], predecessors: [], policy }).ok, true);
  assert.equal(validateReport(critic, { waveRef, wave, slot: topology.slots[2], predecessors: generators, policy }).ok, true);
  const plan = compileWavePlan(waveRef, wave).value; assert.equal(plan.gateRequired, true); assert.equal(verifyWavePlan(plan, topology).ok, true);
});

test('Explore report reconciliation is arrival-order invariant and digest-bound', () => {
  const policy = { version: ref('v'), frameCatalog: [0, 1, 2, 3].map((i) => ({ frameId: `f${i}`, tag: 'code', text: `frame${i}` })).concat([{ frameId: 'wild', tag: 'wild', text: 'wild' }]), maxMaterialDecisions: 4, maxSettlementBytes: 10_000_000, maxResolvedRoleInputBytes: 10_000_000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 };
  const wave = { schema: 'lunacy-deliberation-wave/v2', authorship: { runId: 'r', phaseId: 'p', intent: ref('i'), evidenceSnapshot: ref('e'), authorityDigest: digest('a'), policyVersion: policy.version, settlementPrefixDigest: digest('s'), decisionKey: 'd', prospectiveEffectFrontierOrdinal: 0 }, question: { text: 'q', decisionImpact: 'impact', evidence: [], constraints: [] }, limits: { maxModelCalls: 9, maxWaveBytes: 10_000_000, maxRefs: 500, maxResolvedRoleInputBytes: 10_000_000, maxReportBytes: 1_000_000, maxTotalReportBytes: 10_000_000 }, gear: 'EXPLORE', generatorLenses: [{ frameId: 'f0' }, { frameId: 'f1' }, { frameId: 'f2' }, { frameId: 'f3' }, { frameId: 'wild' }] };
  const waveRef = ref('wave', wave); assert.equal(validateWave(wave, { runId: 'r', phaseId: 'p', policy, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, true); const topology = deriveTopology(waveRef, wave); const generators = Array.from({ length: 5 }, (_, slotOrdinal) => ({ schema: 'lunacy-deliberation-report/v2', wave: waveRef, slotOrdinal, ideas: Array.from({ length: 6 }, (_, i) => ({ text: `idea-${slotOrdinal}-${i}`, rationale: 'because' })) })); const reportRef = (report) => ({ id: `report:${digest(report).slice(0, 16)}`, digest: digest(report), scope: 'deliberation/report', bytes: canonicalString(report) }); const loc = (g, i) => ({ generatorReport: reportRef(g), oneBasedOrdinal: i + 1 }); const scores = generators.flatMap((g, gi) => g.ideas.map((_, i) => ({ idea: loc(g, i), novelty: i === 0 ? 10 : 6, viability: 8, fit: 7, evidence: [] }))); const clusters = [0, 1, 2].map((n) => ({ label: String.fromCharCode(97 + n), ideas: generators.flatMap((g) => g.ideas.map((_, i) => loc(g, i))).filter((_, i) => i % 3 === n) })); const critic = { schema: 'lunacy-deliberation-report/v2', wave: waveRef, slotOrdinal: 5, scores, clusters }; const deepeners = [6, 7, 8].map((slotOrdinal) => ({ schema: 'lunacy-deliberation-report/v2', wave: waveRef, slotOrdinal, sketch: 'One. Two. Three. Four.', loadBearingRisk: 'risk', firstConcreteStep: 'step', childIdeas: ['a', 'b', 'c'] })); const accepted = [...generators, critic, ...deepeners].map((report) => ({ ref: reportRef(report), report, receipt: { commandDigest: digest('cmd'), resultDigest: digest(report), attemptEpoch: 1 } })); const a = reconcileWave(waveRef, wave, accepted); const b = reconcileWave(waveRef, wave, [...accepted].reverse()); assert.equal(a.architecture, 'COMPLETE'); assert.deepEqual(a.reports, b.reports); const forged = { ...accepted[0], ref: { ...accepted[0].ref, digest: digest('forged') }, receipt: { ...accepted[0].receipt, resultDigest: digest('forged') } }; assert.equal(reconcileWave(waveRef, wave, [forged]).architecture, 'CONFLICT');
  const tiedCritic = { ...critic, scores: critic.scores.map((score) => ({ ...score, novelty: 5, viability: 5, fit: 5 })) }; const rendered = renderExplore({ waveRef, wave, reports: [...generators, tiedCritic, ...deepeners], policy }); assert.equal(rendered.ok, true); assert.match(rendered.value.converge, /^1\. ★ idea-0-0/); assert.equal(renderExplore({ waveRef: { ...waveRef, id: 'evil-wave', scope: 'foreign' }, wave, reports: [...generators, critic, ...deepeners], policy }).ok, false);
  const acceptedReportsByRef = new Map(accepted.map((item) => [canonicalString({ id: item.ref.id, digest: item.ref.digest, scope: item.ref.scope }), item])); const resolved = new Map(); for (const g of generators) assert.equal(materializeRoleView({ waveRef, wave, slot: topology.slots[g.slotOrdinal], predecessorRefs: [], acceptedReportsByRef, resolved, policy }).ok, true); assert.equal(materializeRoleView({ waveRef, wave, slot: topology.slots[5], predecessorRefs: generators.map((g) => reportRef(g)), acceptedReportsByRef, resolved, policy }).ok, true); for (const slotOrdinal of [6, 7, 8]) assert.equal(materializeRoleView({ waveRef, wave, slot: topology.slots[slotOrdinal], predecessorRefs: [reportRef(critic)], acceptedReportsByRef, resolved, policy }).ok, true);
  const foreignPolicy = { ...policy, version: ref('foreign-policy', { generation: 2 }), frameCatalog: policy.frameCatalog.map((frame) => ({ ...frame, text: `FOREIGN-${frame.frameId}` })), convergeCount: 2 }; assert.equal(renderExplore({ waveRef, wave, reports: [...generators, critic, ...deepeners], policy: foreignPolicy }).ok, false);
});

test('P2-S10 policy binding is shared and authored Waves self-validate', () => {
  const frames = [0, 1, 2, 3].map((i) => ({ frameId: `f${i}`, tag: i === 3 ? 'design' : 'code', text: `frame-${i}` })).concat([{ frameId: 'wild', tag: 'wild', text: 'wild' }]);
  const policyFor = (generation) => ({ version: ref('policy', { generation }), frameCatalog: frames, maxMaterialDecisions: 4, maxSettlementBytes: 10_000_000, maxResolvedRoleInputBytes: 10_000_000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 });
  const direct = { decisionUnsettled: false, explicitExplore: false, citedWitness: false, planEquivalent: false, containedDiscovery: false, openEnded: false, highStakes: false, openlyPhrased: false, namedDiscriminator: false };
  for (const gear of ['FOCUS', 'EXPLORE']) for (const generation of [1, 2, 3]) {
    const policy = policyFor(generation); const predicates = { ...direct, decisionUnsettled: true, ...(gear === 'EXPLORE' ? { explicitExplore: true } : { namedDiscriminator: true }) }; const result = authorPlan({ runId: 'r', phaseId: 'p', intent: ref('intent'), evidenceSnapshot: ref('snapshot'), authorityDigest: digest('authority'), policyVersion: policy.version, settlements: [] }, predicates, policy); assert.equal(result.kind, 'DELIBERATION_REQUIRED'); const emitted = JSON.parse(result.wave.bytes); assert.equal(validateWave(emitted, { runId: 'r', phaseId: 'p', policy, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, true, `${gear}/${generation}`);
  }
  const policy = policyFor(1); const wave = { schema: 'lunacy-deliberation-wave/v2', authorship: { runId: 'r', phaseId: 'p', intent: ref('intent'), evidenceSnapshot: ref('snapshot'), authorityDigest: digest('authority'), policyVersion: policy.version, settlementPrefixDigest: digest({ domain: 'lunacy/settlement-prefix/v1', settlements: [] }), decisionKey: 'd', prospectiveEffectFrontierOrdinal: 0 }, question: { text: 'q', decisionImpact: 'impact', evidence: [], constraints: [] }, limits: { maxModelCalls: 3, maxWaveBytes: 1_000_000, maxRefs: 128, maxResolvedRoleInputBytes: 1_000_000, maxReportBytes: 200_000, maxTotalReportBytes: 1_000_000 }, gear: 'FOCUS', generatorLenses: [{ text: 'counterexample' }, { text: 'simplify' }] }; const waveRef = ref('wave', wave); const topology = deriveTopology(waveRef, wave); const generator = { schema: 'lunacy-deliberation-report/v2', wave: waveRef, slotOrdinal: 0, ideas: [{ text: 'idea', rationale: 'because' }] }; const foreign = { ...policy, version: ref('policy', { generation: 9 }), frameCatalog: frames.map((frame) => ({ ...frame, text: 'foreign' })) }; assert.equal(materializeRoleView({ waveRef, wave, slot: topology.slots[0], predecessorRefs: [], acceptedReportsByRef: new Map(), resolved: new Map(), policy: foreign }).ok, false); assert.equal(validateReport(generator, { waveRef, wave, slot: topology.slots[0], predecessors: [], policy: foreign }).ok, false);
  const invalidPolicy = { ...policy, frameCatalog: [{ frameId: 'dup', tag: 'code', text: 'a' }, { frameId: 'dup', tag: 'design', text: 'b' }, ...frames.slice(2)] }; const authored = authorPlan({ runId: 'r', phaseId: 'p', intent: ref('intent'), evidenceSnapshot: ref('snapshot'), authorityDigest: digest('authority'), policyVersion: invalidPolicy.version, settlements: [] }, { ...direct, decisionUnsettled: true, explicitExplore: true }, invalidPolicy); assert.equal(authored.kind, 'NO_SETTLEMENT');
});

test('P2-S12 policy numeric domains fail before publication and preserve Direct parity', () => {
  const frames = [0, 1, 2, 3].map((i) => ({ frameId: `f${i}`, tag: i === 3 ? 'design' : 'code', text: `frame-${i}` })).concat([{ frameId: 'wild', tag: 'wild', text: 'wild' }]); const policy = { version: ref('policy', { generation: 1 }), frameCatalog: frames, maxMaterialDecisions: 4, maxSettlementBytes: 10_000_000, maxResolvedRoleInputBytes: 10_000_000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 }; const explorePredicates = { decisionUnsettled: true, explicitExplore: true, citedWitness: false, planEquivalent: false, containedDiscovery: false, openEnded: false, highStakes: false, openlyPhrased: false, namedDiscriminator: false }; const authorship = { runId: 'r', phaseId: 'p', intent: ref('intent'), evidenceSnapshot: ref('snapshot'), authorityDigest: digest('authority'), policyVersion: policy.version, settlements: [] }; const valid = authorPlan(authorship, explorePredicates, policy); assert.equal(valid.kind, 'DELIBERATION_REQUIRED'); const validWave = JSON.parse(valid.wave.bytes); const validWaveRef = valid.wave; assert.equal(validateWave(validWave, { runId: 'r', phaseId: 'p', policy, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, true);
  for (const convergeCount of [2, 4]) { const boundary = { ...policy, convergeCount }; const emitted = authorPlan(authorship, explorePredicates, boundary); assert.equal(emitted.kind, 'DELIBERATION_REQUIRED'); assert.equal(validateWave(JSON.parse(emitted.wave.bytes), { runId: 'r', phaseId: 'p', policy: boundary, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, true); }
  for (const threshold of [0, 10]) for (const key of ['nonObviousNovelty', 'viableFloor']) { const boundary = { ...policy, [key]: threshold }; const emitted = authorPlan(authorship, explorePredicates, boundary); assert.equal(emitted.kind, 'DELIBERATION_REQUIRED'); assert.equal(validateWave(JSON.parse(emitted.wave.bytes), { runId: 'r', phaseId: 'p', policy: boundary, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, true); }
  for (const [key, value] of [['convergeCount', 0], ['convergeCount', 1], ['convergeCount', 5], ['nonObviousNovelty', 11], ['viableFloor', 11], ['nonObviousNovelty', -1], ['viableFloor', -1]]) { const invalid = { ...policy, [key]: value }; assert.equal(authorPlan(authorship, explorePredicates, invalid).kind, 'NO_SETTLEMENT'); assert.equal(validateWave(validWave, { runId: 'r', phaseId: 'p', policy: invalid, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, false); assert.equal(renderExplore({ waveRef: validWaveRef, wave: validWave, reports: [], policy: invalid }).ok, false); }
  const directPlan = validatePlan({ schema: 'lunacy-plan-v1', phaseId: 'p', steps: [{ stepId: 's' }] }).plan; const directIntent = { id: 'direct', digest: digest(directPlan), scope: 'test', bytes: canonicalString(directPlan) }; const malformedPolicy = { ...policy, convergeCount: 0 }; assert.equal(authorPlan({ ...authorship, intent: directIntent }, { decisionUnsettled: false, explicitExplore: false, citedWitness: false, planEquivalent: false, containedDiscovery: false, openEnded: false, highStakes: false, openlyPhrased: false, namedDiscriminator: false }, malformedPolicy).kind, 'COMPLETE_PLAN');
});

test('adversarial bindings fail closed before role work', () => {
  const policy = { version: ref('v'), frameCatalog: [], maxMaterialDecisions: 1, maxSettlementBytes: 10_000, maxResolvedRoleInputBytes: 10_000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 };
  const wave = { schema: 'lunacy-deliberation-wave/v2', authorship: { runId: 'r', phaseId: 'p', intent: ref('i'), evidenceSnapshot: ref('e'), authorityDigest: digest('a'), policyVersion: policy.version, settlementPrefixDigest: digest('s'), decisionKey: 'd', prospectiveEffectFrontierOrdinal: 0 }, question: { text: 'q', decisionImpact: 'impact', evidence: [], constraints: [] }, limits: { maxModelCalls: 3, maxWaveBytes: 10_000, maxRefs: 128, maxResolvedRoleInputBytes: 10_000, maxReportBytes: 2_500, maxTotalReportBytes: 10_000 }, gear: 'FOCUS', generatorLenses: [{ text: 'a' }, { text: 'b' }] };
  assert.equal(validateWave(wave, { runId: 'r', phaseId: 'p', policy: { ...policy, version: ref('other') }, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, false);
  const topology = deriveTopology(ref('wave', wave), wave); const plan = compileWavePlan(ref('wave', wave), wave).value; plan.steps[0].claims = [{ resource: 'workspace', mode: 'WRITE' }]; assert.equal(verifyWavePlan(plan, topology).ok, false);
  const directPlan = { phaseId: 'p', steps: [{ stepId: 's' }] }; const mismatchedIntent = { id: 'intent', digest: digest('wrong'), scope: 'test', bytes: canonicalString(directPlan) }; const direct = { decisionUnsettled: false, explicitExplore: false, citedWitness: false, planEquivalent: false, containedDiscovery: false, openEnded: false, highStakes: false, openlyPhrased: false, namedDiscriminator: false }; assert.equal(authorPlan({ runId: 'r', phaseId: 'p', intent: mismatchedIntent, evidenceSnapshot: ref('e'), authorityDigest: digest('a'), policyVersion: ref('v'), settlements: [] }, direct).kind, 'NO_SETTLEMENT');
  const otherPhasePlan = { phaseId: 'other', steps: [{ stepId: 's' }] }; const otherPhaseIntent = { id: 'intent', digest: digest(otherPhasePlan), scope: 'test', bytes: canonicalString(otherPhasePlan) }; assert.equal(authorPlan({ runId: 'r', phaseId: 'p', intent: otherPhaseIntent, evidenceSnapshot: ref('e'), authorityDigest: digest('a'), policyVersion: ref('v'), settlements: [] }, direct).kind, 'NO_SETTLEMENT');
});

test('P2-S5 shared invariants reject aliases, duplicate frames, foreign closure, and under-budget ladders', () => {
  assert.equal(settlementWitness(unsettled), 'BOUNDED');
  const evidence = ref('evidence', { source: 'sealed' });
  const policy = { version: ref('v'), frameCatalog: [], maxMaterialDecisions: 4, maxSettlementBytes: 1_000_000, maxResolvedRoleInputBytes: 1_000_000, convergeCount: 3, nonObviousNovelty: 5, viableFloor: 5 };
  const wave = { schema: 'lunacy-deliberation-wave/v2', authorship: { runId: 'r', phaseId: 'p', intent: ref('i'), evidenceSnapshot: ref('e'), authorityDigest: digest('a'), policyVersion: policy.version, settlementPrefixDigest: digest('s'), decisionKey: 'd', prospectiveEffectFrontierOrdinal: 0 }, question: { text: 'q', decisionImpact: 'impact', evidence: [evidence], constraints: [] }, limits: { maxModelCalls: 3, maxWaveBytes: 1_000_000, maxRefs: 20, maxResolvedRoleInputBytes: 1_000_000, maxReportBytes: 200_000, maxTotalReportBytes: 1_000_000 }, gear: 'FOCUS', generatorLenses: [{ text: 'counterexample' }, { text: 'simplify' }] };
  assert.equal(validateWave(wave, { runId: 'r', phaseId: 'p', policy, committedEvidence: new Set([evidence.id]), reachableConstraints: new Set() }).ok, false);
  assert.equal(validateWave(wave, { runId: 'r', phaseId: 'p', policy, committedEvidence: new Set([canonicalString({ id: evidence.id, digest: evidence.digest, scope: evidence.scope })]), reachableConstraints: new Set() }).ok, true);
  const topology = deriveTopology(ref('wave', wave), wave); const waveRef = ref('wave', wave); const generator = (slotOrdinal, wr = waveRef) => ({ schema: 'lunacy-deliberation-report/v2', wave: wr, slotOrdinal, ideas: [{ text: `idea-${slotOrdinal}`, rationale: 'because' }] }); const reportRef = (report) => ({ id: `report:${digest(report).slice(0, 16)}`, digest: digest(report), scope: 'deliberation/report', bytes: canonicalString(report) }); const acceptedFor = (report) => ({ ref: reportRef(report), report, receipt: { commandDigest: digest('cmd'), resultDigest: digest(report), attemptEpoch: 1 } }); const foreign = [generator(0, ref('foreign-wave')), generator(1, ref('foreign-wave'))]; const foreignAccepted = foreign.map(acceptedFor); const critic = { schema: 'lunacy-deliberation-report/v2', wave: waveRef, slotOrdinal: 2, scores: [], clusters: [] }; const resolved = new Map([[canonicalString({ id: evidence.id, digest: evidence.digest, scope: evidence.scope }), { ref: evidence, bytes: evidence.bytes, size: Buffer.byteLength(evidence.bytes, 'utf8') }]]); assert.equal(materializeRoleView({ waveRef, wave, slot: topology.slots[2], predecessorRefs: foreignAccepted.map((item) => item.ref), acceptedReportsByRef: new Map(foreignAccepted.map((item) => [canonicalString({ id: item.ref.id, digest: item.ref.digest, scope: item.ref.scope }), item])), resolved, policy }).ok, false); assert.equal(validateReport(critic, { waveRef, wave, slot: topology.slots[2], predecessors: foreign, policy }).ok, false); assert.equal(validateReport(critic, { waveRef, wave, slot: topology.slots[2], predecessors: [generator(1), generator(0)], policy }).ok, false);
  const generators = [generator(0), generator(1)]; const repeated = Array.from({ length: 5 }, () => evidence); const scores = generators.map((g) => ({ idea: { generatorReport: reportRef(g), oneBasedOrdinal: 1 }, novelty: 5, viability: 5, fit: 5, evidence: repeated })); const evidenceHeavy = { ...critic, scores, clusters: [{ label: 'a', ideas: [{ generatorReport: reportRef(generators[0]), oneBasedOrdinal: 1 }] }, { label: 'b', ideas: [{ generatorReport: reportRef(generators[1]), oneBasedOrdinal: 1 }] }, { label: 'c', ideas: [] }] }; assert.equal(validateReport(evidenceHeavy, { waveRef, wave, slot: topology.slots[2], predecessors: generators, policy }).ok, false);
  const malformed = { ...generator(0), ideas: [] }; const validAccepted = generators.map(acceptedFor); const malformedAccepted = [acceptedFor(malformed), ...validAccepted.slice(1)]; const malformedIndex = new Map(malformedAccepted.map((item) => [canonicalString({ id: item.ref.id, digest: item.ref.digest, scope: item.ref.scope }), item])); const roleResolved = new Map([[canonicalString({ id: evidence.id, digest: evidence.digest, scope: evidence.scope }), { ref: evidence, bytes: evidence.bytes, size: Buffer.byteLength(evidence.bytes, 'utf8') }]]); assert.equal(materializeRoleView({ waveRef, wave, slot: topology.slots[2], predecessorRefs: malformedAccepted.map((item) => item.ref), acceptedReportsByRef: malformedIndex, resolved: roleResolved, policy }).ok, false); const foreignValue = ref('foreign-value'); const forgedResolved = new Map([[canonicalString({ id: evidence.id, digest: evidence.digest, scope: evidence.scope }), { ref: foreignValue, bytes: evidence.bytes, size: Buffer.byteLength(evidence.bytes, 'utf8') }]]); assert.equal(materializeRoleView({ waveRef, wave, slot: topology.slots[0], predecessorRefs: [], acceptedReportsByRef: new Map(), resolved: forgedResolved, policy }).ok, false); const arbitraryResolved = new Map([[canonicalString({ id: evidence.id, digest: evidence.digest, scope: evidence.scope }), { ref: evidence, bytes: canonicalString({ arbitrary: true }), size: Buffer.byteLength(canonicalString({ arbitrary: true }), 'utf8') }]]); assert.equal(materializeRoleView({ waveRef, wave, slot: topology.slots[0], predecessorRefs: [], acceptedReportsByRef: new Map(), resolved: arbitraryResolved, policy }).ok, false); const forgedSlot = { ...topology.slots[0], dependencies: [5] }; assert.equal(materializeRoleView({ waveRef, wave, slot: forgedSlot, predecessorRefs: [], acceptedReportsByRef: new Map(), resolved: roleResolved, policy }).ok, false); assert.equal(validateReport(generators[0], { waveRef, wave, slot: forgedSlot, predecessors: [], policy }).ok, false);
  const explorePolicy = { ...policy, frameCatalog: [{ frameId: 'f0', tag: 'code', text: '0' }, { frameId: 'f0', tag: 'design', text: 'duplicate' }, { frameId: 'f1', tag: 'code', text: '1' }, { frameId: 'f2', tag: 'code', text: '2' }, { frameId: 'f3', tag: 'design', text: '3' }, { frameId: 'wild', tag: 'wild', text: 'wild' }] }; const explore = { ...wave, limits: { ...wave.limits, maxModelCalls: 9, maxRefs: 63 }, gear: 'EXPLORE', generatorLenses: [{ frameId: 'f0' }, { frameId: 'f1' }, { frameId: 'f2' }, { frameId: 'f3' }, { frameId: 'wild' }] }; assert.equal(validateWave(explore, { runId: 'r', phaseId: 'p', policy: explorePolicy, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, false); assert.equal(validateWave(explore, { runId: 'r', phaseId: 'p', policy: { ...explorePolicy, frameCatalog: explorePolicy.frameCatalog.filter((f, i) => i !== 1) }, committedEvidence: new Set(), reachableConstraints: new Set() }).ok, false);
});
