"""Deterministic, read-only package inventory receipts for maintainer checks.

This helper intentionally lives outside the installed skill. Creating a receipt
reads the package and writes only a new requested receipt path; verification reads
both inputs and never mutates the package or installs anything. Inventory is safe
only for a trusted, quiescent tree: the lstat/open sequence is not a defense against
hostile concurrent replacement. ``packageIdentity`` and source claims are supplied
by the caller; they are labels, not manifest identity or source attestation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import sys
from pathlib import Path, PurePosixPath
from typing import Any


FORMAT = "lunacy-package-receipt-v1"


class ReceiptError(ValueError):
    """Raised when a package or receipt cannot satisfy the strict contract."""


def _ensure_package_dir(package_dir: Path) -> Path:
    package_dir = Path(package_dir)
    if package_dir.is_symlink() or not package_dir.is_dir():
        raise ReceiptError(f"package directory is not a real directory: {package_dir}")
    return package_dir


def _walk_files(package_dir: Path) -> list[dict[str, Any]]:
    """Return a stable regular-file inventory, rejecting unsafe entries."""

    root = _ensure_package_dir(package_dir)
    entries: list[dict[str, Any]] = []
    stack = [root]
    while stack:
        current = stack.pop()
        children = sorted(current.iterdir(), key=lambda item: item.name, reverse=True)
        for child in children:
            relative = child.relative_to(root)
            if "__pycache__" in relative.parts or child.suffix in {".pyc", ".pyo"}:
                raise ReceiptError(f"generated bytecode is not allowed: {relative.as_posix()}")
            mode = child.lstat().st_mode
            if stat.S_ISLNK(mode):
                raise ReceiptError(f"symlink is not allowed: {relative.as_posix()}")
            if stat.S_ISDIR(mode):
                stack.append(child)
                continue
            if not stat.S_ISREG(mode):
                raise ReceiptError(f"special file is not allowed: {relative.as_posix()}")
            digest = hashlib.sha256()
            with child.open("rb") as stream:
                for block in iter(lambda: stream.read(1024 * 1024), b""):
                    digest.update(block)
            entries.append(
                {
                    "path": PurePosixPath(relative.as_posix()).as_posix(),
                    "size": child.stat().st_size,
                    "sha256": digest.hexdigest(),
                }
            )
    entries.sort(key=lambda entry: entry["path"])
    return entries


def _claim(value: str | None, label: str) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip():
        raise ReceiptError(f"{label} source claim must be a non-empty string")
    return value


def create_receipt(
    package_dir: str | os.PathLike[str],
    package_identity: str,
    *,
    source_base: str | None = None,
    source_patch: str | None = None,
) -> dict[str, Any]:
    """Create a receipt object without mutating ``package_dir``."""

    if not isinstance(package_identity, str) or not package_identity.strip():
        raise ReceiptError("package identity must be a non-empty string")
    files = _walk_files(Path(package_dir))
    return {
        "format": FORMAT,
        "packageIdentity": package_identity,
        "sourceClaims": {
            "base": _claim(source_base, "base"),
            "patch": _claim(source_patch, "patch"),
            "proven": False,
        },
        "files": files,
    }


def write_receipt(
    receipt: dict[str, Any],
    output: str | os.PathLike[str],
    *,
    package_dir: str | os.PathLike[str] | None = None,
) -> None:
    """Exclusively write canonical JSON outside ``package_dir`` when supplied."""

    target = Path(output)
    if package_dir is not None:
        root = _ensure_package_dir(Path(package_dir)).resolve(strict=True)
        resolved_target = target.resolve(strict=False)
        if resolved_target == root or root in resolved_target.parents:
            raise ReceiptError(f"receipt output must be outside package directory: {target}")
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        descriptor = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o666)
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(json.dumps(receipt, sort_keys=True, indent=2) + "\n")
    except FileExistsError as exc:
        raise ReceiptError(f"receipt output already exists: {target}") from exc
    except OSError as exc:
        raise ReceiptError(f"cannot write receipt output {target}: {exc}") from exc


def _validated_expected(receipt: Any) -> list[dict[str, Any]]:
    if not isinstance(receipt, dict) or receipt.get("format") != FORMAT:
        raise ReceiptError("receipt format is unsupported")
    identity = receipt.get("packageIdentity")
    if not isinstance(identity, str) or not identity.strip():
        raise ReceiptError("receipt packageIdentity is missing")
    claims = receipt.get("sourceClaims")
    if not isinstance(claims, dict) or claims.get("proven") is not False:
        raise ReceiptError("source claims must be explicitly unproven")
    for key in ("base", "patch"):
        value = claims.get(key)
        if value is not None and (not isinstance(value, str) or not value.strip()):
            raise ReceiptError(f"receipt sourceClaims.{key} is invalid")
    files = receipt.get("files")
    if not isinstance(files, list):
        raise ReceiptError("receipt files must be a list")
    seen: set[str] = set()
    validated: list[dict[str, Any]] = []
    for entry in files:
        if not isinstance(entry, dict):
            raise ReceiptError("receipt file entry is not an object")
        path = entry.get("path")
        if not isinstance(path, str) or not path or PurePosixPath(path).is_absolute():
            raise ReceiptError("receipt file path is not relative")
        parts = PurePosixPath(path).parts
        if ".." in parts or "." in parts or "__pycache__" in parts or path in seen:
            raise ReceiptError(f"receipt file path is unsafe or duplicated: {path}")
        size = entry.get("size")
        digest = entry.get("sha256")
        if not isinstance(size, int) or isinstance(size, bool) or size < 0:
            raise ReceiptError(f"receipt size is invalid: {path}")
        if not isinstance(digest, str) or len(digest) != 64 or any(c not in "0123456789abcdef" for c in digest):
            raise ReceiptError(f"receipt digest is invalid: {path}")
        seen.add(path)
        validated.append({"path": path, "size": size, "sha256": digest})
    return sorted(validated, key=lambda entry: entry["path"])


def verify_receipt(
    package_dir: str | os.PathLike[str], receipt_path: str | os.PathLike[str] | dict[str, Any]
) -> None:
    """Verify exact file membership, sizes, and digests without writing."""

    if isinstance(receipt_path, dict):
        receipt = receipt_path
    else:
        try:
            receipt = json.loads(Path(receipt_path).read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ReceiptError(f"cannot read receipt: {exc}") from exc
    expected = _validated_expected(receipt)
    actual = _walk_files(Path(package_dir))
    expected_by_path = {entry["path"]: entry for entry in expected}
    actual_by_path = {entry["path"]: entry for entry in actual}
    problems: list[str] = []
    for path in sorted(set(expected_by_path) - set(actual_by_path)):
        problems.append(f"deleted: {path}")
    for path in sorted(set(actual_by_path) - set(expected_by_path)):
        problems.append(f"added: {path}")
    for path in sorted(set(expected_by_path) & set(actual_by_path)):
        if expected_by_path[path] != actual_by_path[path]:
            problems.append(f"changed: {path}")
    if problems:
        raise ReceiptError("package does not match receipt (" + "; ".join(problems) + ")")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    create = commands.add_parser("create")
    create.add_argument("--package-dir", required=True, type=Path)
    create.add_argument("--identity", required=True)
    create.add_argument("--source-base")
    create.add_argument("--source-patch")
    create.add_argument("--output", required=True, type=Path)
    verify = commands.add_parser("verify")
    verify.add_argument("--package-dir", required=True, type=Path)
    verify.add_argument("--receipt", required=True, type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    try:
        args = _parser().parse_args(argv)
        if args.command == "create":
            receipt = create_receipt(
                args.package_dir,
                args.identity,
                source_base=args.source_base,
                source_patch=args.source_patch,
            )
            write_receipt(receipt, args.output, package_dir=args.package_dir)
        else:
            verify_receipt(args.package_dir, args.receipt)
    except (ReceiptError, OSError) as exc:
        print(f"receipt error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
